image: Visual Studio 2017 # образ для сборки
stack: node 18 # версия Node.js
branches:
  only:
    - main  # ветка git
cache: node_modules  # кэширование
install:
  - npm install  # команда установки зависимостей
build: off
test_script:
  - npm run lint && npm test  # скрипт сборки