image: Visual Studio 2017 # образ для сборки
environment:
  nodejs_version: "18"
stack: node 18 # версия Node.js
branches:
  only:
    - main  # ветка git
cache: node_modules  # кэширование
install:
  - nvm install $env:nodejs_version
  - nvm use $env:nodejs_version
  - node --version
  - npm install  # команда установки зависимостей
build: off
test_script:
  - npm run lint && npm test  # скрипт сборки